### ISSUE TITLE
No such directory hard_signatures/unpacked_SHA256-Hashes_packs

### ISSUE THREAD

**Issue by MandiYang** [cookie0o/Python-Antivirus-v2#2]
In Antivirus.py Line 16-17:
```
# Hashes path
HASH_Files          = (current_dir + '/hard_signatures/unpacked_SHA256-Hashes_packs/')
```
There isn't any directory named  `unpacked_SHA256-Hashes_packs` to download the files from virusshare, adding it would solve the issue.

**Comment by cookie0o** [comment]
I hope v3.0 fixed your issue!
