### ISSUE TITLE
Error in code and code not running 

### ISSUE THREAD

**Issue by linuxchuck-hz** [cookie0o/Python-Antivirus-v2#3]
![3](https://user-images.githubusercontent.com/80969585/217563467-56dc6858-dcd0-4b99-b0eb-02c1e8fc2175.png)
![5](https://user-images.githubusercontent.com/80969585/217563380-04330345-b529-4ee3-9a2d-e87b5177cc2b.png)
![4](https://user-images.githubusercontent.com/80969585/217563427-45a2af30-b089-41f8-853e-6aea4c43c889.png)

**Comment by cookie0o** [comment]
looks like I forgot to add some packages in `requirements.txt` will add them dor now run: `pip install qt_material`, I hope this will fix ur issue

**Comment by linuxchuck-hz** [comment]
Thank You Very Much
